// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rom", '{
        '{32'h00100000, 32'h00100fff}
    }},
    '{"sram", '{
        '{32'h00200000, 32'h0027ffff}
    }},
    '{"revocation_ram", '{
        '{32'h00300000, 32'h00301fff}
    }},
    '{"rev_ctl", '{
        '{32'h00340000, 32'h00340fff}
    }},
    '{"core_ibex__cfg", '{
        '{32'h811f0000, 32'h811f0fff}
    }},
    '{"dbg_mem", '{
        '{32'hb0000000, 32'hb0000fff}
    }},
    '{"rv_plic", '{
        '{32'h88000000, 32'h8bffffff}
    }},
    '{"peri", '{
        '{32'h40000000, 32'h7fffffff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"core_ibex__corei", 0, '{
        "sram",
        "rom",
        "dbg_mem"}}
    ,
    '{"core_ibex__cored", 1, '{
        "sram",
        "rom",
        "revocation_ram",
        "rev_ctl",
        "core_ibex__cfg",
        "rv_plic",
        "peri"}}
    ,
    '{"dbg", 2, '{
        "sram",
        "rom",
        "revocation_ram",
        "rev_ctl",
        "core_ibex__cfg",
        "rv_plic",
        "peri"}}
};
