// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_main_bind module generated by `tlgen.py` tool for assertions
module xbar_main_bind;
`ifndef GATE_LEVEL
  // Host interfaces
  bind xbar_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_rv_core_ibex__corei (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_rv_core_ibex__corei_i),
    .d2h    (tl_rv_core_ibex__corei_o)
  );
  bind xbar_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_rv_core_ibex__cored (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_rv_core_ibex__cored_i),
    .d2h    (tl_rv_core_ibex__cored_o)
  );

  // Device interfaces
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_rom (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_rom_o),
    .d2h    (tl_rom_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_sram (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_sram_o),
    .d2h    (tl_sram_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_revocation_ram (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_revocation_ram_o),
    .d2h    (tl_revocation_ram_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_rv_plic (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_rv_plic_o),
    .d2h    (tl_rv_plic_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_peri (
    .clk_i  (clk_peri_i),
    .rst_ni (rst_peri_ni),
    .h2d    (tl_peri_o),
    .d2h    (tl_peri_i)
  );
`endif
endmodule
