// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rom", '{
        '{32'h00100000, 32'h00100fff}
    }},
    '{"sram", '{
        '{32'h00200000, 32'h0023ffff}
    }},
    '{"revocation_ram", '{
        '{32'h00300000, 32'h003007ff}
    }},
    '{"peri", '{
        '{32'h40000000, 32'h7fffffff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"rv_core_ibex__corei", 0, '{
        "sram",
        "rom"}}
    ,
    '{"rv_core_ibex__cored", 1, '{
        "sram",
        "rom",
        "revocation_ram",
        "peri"}}
};
