// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_peri module generated by `tlgen.py` tool
// all reset signals should be generated from one reset signal to not make any deadlock
//
// Interconnect
// main
//   -> s1n_11
//     -> rv_timer
//     -> aon_timer
//     -> gpio
//     -> i2c0
//     -> i2c1
//     -> spi_host0
//     -> spi_host1
//     -> uart0
//     -> uart1
//     -> asf_12
//       -> usbdev

module xbar_peri (
  input clk_peri_i,
  input clk_usb_i,
  input rst_peri_ni,
  input rst_usb_ni,

  // Host interfaces
  input  tlul_pkg::tl_h2d_t tl_main_i,
  output tlul_pkg::tl_d2h_t tl_main_o,

  // Device interfaces
  output tlul_pkg::tl_h2d_t tl_aon_timer_o,
  input  tlul_pkg::tl_d2h_t tl_aon_timer_i,
  output tlul_pkg::tl_h2d_t tl_rv_timer_o,
  input  tlul_pkg::tl_d2h_t tl_rv_timer_i,
  output tlul_pkg::tl_h2d_t tl_gpio_o,
  input  tlul_pkg::tl_d2h_t tl_gpio_i,
  output tlul_pkg::tl_h2d_t tl_i2c0_o,
  input  tlul_pkg::tl_d2h_t tl_i2c0_i,
  output tlul_pkg::tl_h2d_t tl_i2c1_o,
  input  tlul_pkg::tl_d2h_t tl_i2c1_i,
  output tlul_pkg::tl_h2d_t tl_spi_host0_o,
  input  tlul_pkg::tl_d2h_t tl_spi_host0_i,
  output tlul_pkg::tl_h2d_t tl_spi_host1_o,
  input  tlul_pkg::tl_d2h_t tl_spi_host1_i,
  output tlul_pkg::tl_h2d_t tl_uart0_o,
  input  tlul_pkg::tl_d2h_t tl_uart0_i,
  output tlul_pkg::tl_h2d_t tl_uart1_o,
  input  tlul_pkg::tl_d2h_t tl_uart1_i,
  output tlul_pkg::tl_h2d_t tl_usbdev_o,
  input  tlul_pkg::tl_d2h_t tl_usbdev_i,

  input prim_mubi_pkg::mubi4_t scanmode_i
);

  import tlul_pkg::*;
  import tl_peri_pkg::*;

  // scanmode_i is currently not used, but provisioned for future use
  // this assignment prevents lint warnings
  logic unused_scanmode;
  assign unused_scanmode = ^scanmode_i;

  tl_h2d_t tl_s1n_11_us_h2d ;
  tl_d2h_t tl_s1n_11_us_d2h ;


  tl_h2d_t tl_s1n_11_ds_h2d [10];
  tl_d2h_t tl_s1n_11_ds_d2h [10];

  // Create steering signal
  logic [3:0] dev_sel_s1n_11;

  tl_h2d_t tl_asf_12_us_h2d ;
  tl_d2h_t tl_asf_12_us_d2h ;
  tl_h2d_t tl_asf_12_ds_h2d ;
  tl_d2h_t tl_asf_12_ds_d2h ;



  assign tl_rv_timer_o = tl_s1n_11_ds_h2d[0];
  assign tl_s1n_11_ds_d2h[0] = tl_rv_timer_i;

  assign tl_aon_timer_o = tl_s1n_11_ds_h2d[1];
  assign tl_s1n_11_ds_d2h[1] = tl_aon_timer_i;

  assign tl_gpio_o = tl_s1n_11_ds_h2d[2];
  assign tl_s1n_11_ds_d2h[2] = tl_gpio_i;

  assign tl_i2c0_o = tl_s1n_11_ds_h2d[3];
  assign tl_s1n_11_ds_d2h[3] = tl_i2c0_i;

  assign tl_i2c1_o = tl_s1n_11_ds_h2d[4];
  assign tl_s1n_11_ds_d2h[4] = tl_i2c1_i;

  assign tl_spi_host0_o = tl_s1n_11_ds_h2d[5];
  assign tl_s1n_11_ds_d2h[5] = tl_spi_host0_i;

  assign tl_spi_host1_o = tl_s1n_11_ds_h2d[6];
  assign tl_s1n_11_ds_d2h[6] = tl_spi_host1_i;

  assign tl_uart0_o = tl_s1n_11_ds_h2d[7];
  assign tl_s1n_11_ds_d2h[7] = tl_uart0_i;

  assign tl_uart1_o = tl_s1n_11_ds_h2d[8];
  assign tl_s1n_11_ds_d2h[8] = tl_uart1_i;

  assign tl_asf_12_us_h2d = tl_s1n_11_ds_h2d[9];
  assign tl_s1n_11_ds_d2h[9] = tl_asf_12_us_d2h;

  assign tl_s1n_11_us_h2d = tl_main_i;
  assign tl_main_o = tl_s1n_11_us_d2h;

  assign tl_usbdev_o = tl_asf_12_ds_h2d;
  assign tl_asf_12_ds_d2h = tl_usbdev_i;

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_11 = 4'd10;
    if ((tl_s1n_11_us_h2d.a_address &
         ~(ADDR_MASK_RV_TIMER)) == ADDR_SPACE_RV_TIMER) begin
      dev_sel_s1n_11 = 4'd0;

    end else if ((tl_s1n_11_us_h2d.a_address &
                  ~(ADDR_MASK_AON_TIMER)) == ADDR_SPACE_AON_TIMER) begin
      dev_sel_s1n_11 = 4'd1;

    end else if ((tl_s1n_11_us_h2d.a_address &
                  ~(ADDR_MASK_GPIO)) == ADDR_SPACE_GPIO) begin
      dev_sel_s1n_11 = 4'd2;

    end else if ((tl_s1n_11_us_h2d.a_address &
                  ~(ADDR_MASK_I2C0)) == ADDR_SPACE_I2C0) begin
      dev_sel_s1n_11 = 4'd3;

    end else if ((tl_s1n_11_us_h2d.a_address &
                  ~(ADDR_MASK_I2C1)) == ADDR_SPACE_I2C1) begin
      dev_sel_s1n_11 = 4'd4;

    end else if ((tl_s1n_11_us_h2d.a_address &
                  ~(ADDR_MASK_SPI_HOST0)) == ADDR_SPACE_SPI_HOST0) begin
      dev_sel_s1n_11 = 4'd5;

    end else if ((tl_s1n_11_us_h2d.a_address &
                  ~(ADDR_MASK_SPI_HOST1)) == ADDR_SPACE_SPI_HOST1) begin
      dev_sel_s1n_11 = 4'd6;

    end else if ((tl_s1n_11_us_h2d.a_address &
                  ~(ADDR_MASK_UART0)) == ADDR_SPACE_UART0) begin
      dev_sel_s1n_11 = 4'd7;

    end else if ((tl_s1n_11_us_h2d.a_address &
                  ~(ADDR_MASK_UART1)) == ADDR_SPACE_UART1) begin
      dev_sel_s1n_11 = 4'd8;

    end else if ((tl_s1n_11_us_h2d.a_address &
                  ~(ADDR_MASK_USBDEV)) == ADDR_SPACE_USBDEV) begin
      dev_sel_s1n_11 = 4'd9;
end
  end


  // Instantiation phase
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (40'h0),
    .DRspDepth (40'h0),
    .N         (10)
  ) u_s1n_11 (
    .clk_i        (clk_peri_i),
    .rst_ni       (rst_peri_ni),
    .tl_h_i       (tl_s1n_11_us_h2d),
    .tl_h_o       (tl_s1n_11_us_d2h),
    .tl_d_o       (tl_s1n_11_ds_h2d),
    .tl_d_i       (tl_s1n_11_ds_d2h),
    .dev_select_i (dev_sel_s1n_11)
  );
  tlul_fifo_async #(
    .ReqDepth        (1),
    .RspDepth        (1)
  ) u_asf_12 (
    .clk_h_i      (clk_peri_i),
    .rst_h_ni     (rst_peri_ni),
    .clk_d_i      (clk_usb_i),
    .rst_d_ni     (rst_usb_ni),
    .tl_h_i       (tl_asf_12_us_h2d),
    .tl_h_o       (tl_asf_12_us_d2h),
    .tl_d_o       (tl_asf_12_ds_h2d),
    .tl_d_i       (tl_asf_12_ds_d2h)
  );

endmodule
