// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tb__xbar_connect generated by `tlgen.py` tool

xbar_peri dut();

`DRIVE_CLK(clk_peri_i)

initial force dut.clk_peri_i = clk_peri_i;

// TODO, all resets tie together
initial force dut.rst_peri_ni = rst_n;

// Host TileLink interface connections
`CONNECT_TL_HOST_IF(main, dut, clk_peri_i, rst_n)

// Device TileLink interface connections
`CONNECT_TL_DEVICE_IF(aon_timer, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(rv_timer, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(gpio, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(i2c0, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(i2c1, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(spi_host0, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(spi_host1, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(uart0, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(uart1, dut, clk_peri_i, rst_n)
