name: Sunburst chip tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-reqs:
    name: Python requirements
    runs-on: ubuntu-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v4
    - name: Python virtual environment setup
      run: |
        set -e
        python3 -m venv ./sunburst-py-venv
        source ./sunburst-py-venv/bin/activate
        pip3 install -U pip "setuptools<66.0.0"
        pip3 install -r ./python-requirements.txt

  simulator:
    name: Simulator
    runs-on: nixos

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        extra_nix_config: |
          substituters = https://nix-cache.lowrisc.org/public/ https://cache.nixos.org/
          trusted-public-keys = nix-cache.lowrisc.org-public-1:O6JLD0yXzaJDPiQW1meVu32JIDViuaPtGDfjlOopU7o= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: Build simulator
      run: nix build .#sunburst_simulator -L
